BASE_URL = "https://api-test.mopinion.com"
TOKEN_PATH = "/token"
VERSION = "1.18.14"
VERBOSITY = "normal"
MAX_RETRIES = 3
VERBOSITY_lEVELS = ["quiet", "normal", "full"]
ITERATE_VERBOSITY_lEVELS = ["normal", "full"]
ALLOWED_METHODS = ["get", "post", "put", "delete", "options"]
VERSIONS = ["1.18.14", "2.0.0"]
CONTENT_NEGOTIATIONS = ["application/json", "application/x-yaml"]
