# Run test for master and release branches

name: Test Suite
on:
  push:
    branches:
     - master
     - release-**

  pull_request:
    branches:
      - master
      - release-**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests mock dataclasses

      - name: Test with pytest
        run: |
          pytest

#  # to be done: https://github.com/marketplace/actions/coveralls-python#coveragepy-configuration
#  coveralls_finish:
#    needs: test
#    runs-on: ubuntu-latest
#    steps:
#    - name: Coveralls Finished
#      uses: AndreMiras/coveralls-python-action@develop
#      with:
#        parallel-finished: true
